# <span style="color:red"> DATASCI 151 - Practice Quiz #4 </span>

<font size = "4" >
This quiz is open book 

<br>

- You <span style="color:red"> CAN </span> use all material from the course repo

- You should <span style="color:red"> NOT </span> use other resources outside the course repo.

- You should <span style="color:red"> NOT </span> collaborate with other students

- Use of LLMs or any AI tools is <span style="color:red"> NOT ALLOWED </span>

- To get full credit, the code should work as intended. But try to attempt every problem - you can still receive partial credit.

<br>

Print the following string:

"I will abide by Emory's code of conduct"

In [ ]:
print()

<font size = "4">

Import the libraries `numpy`, `matplotlib.pyplot`, and `pandas`. You probably want to give them aliases (nicknames) but it's not required.

In [1]:
# import libraries
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

<font size = "4">

**Q1** Random Assignment

<font size = "3">

- Read in the dataset named "fifa23_players_basic.csv", assigning it to a DataFrame object. Each row of the dataset corresponds to a professional soccer (football) player.

- Use some method to randomly assign each player into two groups: "A" and "B". Each group should be assigned with equal probability (50% chance of being placed in either group). You can use any appropriate method to perform the random assignment.

- Add a new column to the DataFrame with the name "Group", where each entry is either the string "A" or "B".

In [4]:
# your code here
fifa = pd.read_csv("quiz_data/fifa23_players_basic.csv")

nrows, ncols = fifa.shape

randomcol = np.random.choice(["A", "B"], size = nrows)

fifa["Group"] = randomcol

<font size = "4">

**Q2** Plotting two groups

<font size = "3">

- Continue to use the DataFrame you created in Q1

- Use `.query` to extract all players in Group "A", assigning it to a new DataFrame called `groupA`

- Use `.query` to extract all players in Group "B", assigning it to a new DataFrame called `groupB`

- Use ``matplotlib.pyplot.subplots`` to create two side by side scatter plots (1 row, 2 columns)

- In the left figure, plot the columns ``Age`` vs. ``Overall`` for the data in ``groupA`` (so the horizontal axis will correspond to "Age")
- In the right figure, plot the columns ``Age`` vs. ``Overall`` for the data in ``groupB`` (so the horizontal axis will correspond to "Age")
- Label the axes for both plots. Create a title for **both** plots, indicating whether Group A or Group B is shown.

**Note**: If the assignment into groups was done randomly, then we expect that the scatter plots will be **very similar**

**Hint**: ``matplotlib.pyplot.subplots`` was used in the Lecture 09 notebook on Random Variables. Solve the problem using two executions of `matplotlib.pyplot.scatter` first, then review how to use subplots.

In [ ]:
# your code here
groupA = fifa.query("Group == 'A'")
groupB = fifa.query("Group == 'B'")

fig, subplt = plt.subplots(nrows = 1, ncols = 2)

subplt[0].scatter(x = groupA["Age"], y = groupA["Overall"])

Help on function subplots in module matplotlib.pyplot:

subplots(
    nrows: 'int' = 1,
    ncols: 'int' = 1,
    *,
    sharex: "bool | Literal['none', 'all', 'row', 'col']" = False,
    sharey: "bool | Literal['none', 'all', 'row', 'col']" = False,
    squeeze: 'bool' = True,
    width_ratios: 'Sequence[float] | None' = None,
    height_ratios: 'Sequence[float] | None' = None,
    subplot_kw: 'dict[str, Any] | None' = None,
    gridspec_kw: 'dict[str, Any] | None' = None,
    **fig_kw
) -> 'tuple[Figure, Any]'
    Create a figure and a set of subplots.

    This utility wrapper makes it convenient to create common layouts of
    subplots, including the enclosing figure object, in a single call.

    Parameters
    ----------
    nrows, ncols : int, default: 1
        Number of rows/columns of the subplot grid.

    sharex, sharey : bool or {'none', 'all', 'row', 'col'}, default: False
        Controls sharing of properties among x (*sharex*) or y (*sharey*)
        axes:

        - True or 'all': x- or y-axis will be shared among all subplots.
        - False or 'none': each subplot x- or y-axis will be independent.
        - 'row': each subplot row will share an x- or y-axis.
        - 'col': each subplot column will share an x- or y-axis.

        When subplots have a shared x-axis along a column, only the x tick
        labels of the bottom subplot are created. Similarly, when subplots
        have a shared y-axis along a row, only the y tick labels of the first
        column subplot are created. To later turn other subplots' ticklabels
        on, use `~matplotlib.axes.Axes.tick_params`.

        When subplots have a shared axis that has units, calling
        `.Axis.set_units` will update each axis with the new units.

        Note that it is not possible to unshare axes.

    squeeze : bool, default: True
        - If True, extra dimensions are squeezed out from the returned
          array of `~matplotlib.axes.Axes`:

          - if only one subplot is constructed (nrows=ncols=1), the
            resulting single Axes object is returned as a scalar.
          - for Nx1 or 1xM subplots, the returned object is a 1D numpy
            object array of Axes objects.
          - for NxM, subplots with N>1 and M>1 are returned as a 2D array.

        - If False, no squeezing at all is done: the returned Axes object is
          always a 2D array containing Axes instances, even if it ends up
          being 1x1.

    width_ratios : array-like of length *ncols*, optional
        Defines the relative widths of the columns. Each column gets a
        relative width of ``width_ratios[i] / sum(width_ratios)``.
        If not given, all columns will have the same width.  Equivalent
        to ``gridspec_kw={'width_ratios': [...]}``.

    height_ratios : array-like of length *nrows*, optional
        Defines the relative heights of the rows. Each row gets a
        relative height of ``height_ratios[i] / sum(height_ratios)``.
        If not given, all rows will have the same height. Convenience
        for ``gridspec_kw={'height_ratios': [...]}``.

    subplot_kw : dict, optional
        Dict with keywords passed to the
        `~matplotlib.figure.Figure.add_subplot` call used to create each
        subplot.

    gridspec_kw : dict, optional
        Dict with keywords passed to the `~matplotlib.gridspec.GridSpec`
        constructor used to create the grid the subplots are placed on.

    **fig_kw
        All additional keyword arguments are passed to the
        `.pyplot.figure` call.

    Returns
    -------
    fig : `.Figure`

    ax : `~matplotlib.axes.Axes` or array of Axes
        *ax* can be either a single `~.axes.Axes` object, or an array of Axes
        objects if more than one subplot was created.  The dimensions of the
        resulting array can be controlled with the squeeze keyword, see above.

        Typical idioms for handling the return value are::

            # using the variable ax for single a Axes
            fig, ax = plt.subplots()

            # using the variable axs for multiple Axes
            fig, axs = plt.subplots(2, 2)

            # using tuple unpacking for multiple Axes
            fig, (ax1, ax2) = plt.subplots(1, 2)
            fig, ((ax1, ax2), (ax3, ax4)) = plt.subplots(2, 2)

        The names ``ax`` and pluralized ``axs`` are preferred over ``axes``
        because for the latter it's not clear if it refers to a single
        `~.axes.Axes` instance or a collection of these.

    See Also
    --------
    .pyplot.figure
    .pyplot.subplot
    .pyplot.axes
    .Figure.subplots
    .Figure.add_subplot

    Examples
    --------
    ::

        # First create some toy data:
        x = np.linspace(0, 2*np.pi, 400)
        y = np.sin(x**2)

        # Create just a figure and only one subplot
        fig, ax = plt.subplots()
        ax.plot(x, y)
        ax.set_title('Simple plot')

        # Create two subplots and unpack the output array immediately
        f, (ax1, ax2) = plt.subplots(1, 2, sharey=True)
        ax1.plot(x, y)
        ax1.set_title('Sharing Y axis')
        ax2.scatter(x, y)

        # Create four polar Axes and access them through the returned array
        fig, axs = plt.subplots(2, 2, subplot_kw=dict(projection="polar"))
        axs[0, 0].plot(x, y)
        axs[1, 1].scatter(x, y)

        # Share a X axis with each column of subplots
        plt.subplots(2, 2, sharex='col')

        # Share a Y axis with each row of subplots
        plt.subplots(2, 2, sharey='row')

        # Share both X and Y axes with all subplots
        plt.subplots(2, 2, sharex='all', sharey='all')

        # Note that this is the same as
        plt.subplots(2, 2, sharex=True, sharey=True)

        # Create figure number 10 with a single subplot
        # and clears it if it already exists.
        fig, ax = plt.subplots(num=10, clear=True)

<font size = "4">

**Q3** Merging DataFrames

<font size = "3">

In the code cell below, a Pandas DataFrame is created manually based on the [four statistical regions defined by the U.S. Census Bureau](https://en.wikipedia.org/wiki/List_of_regions_of_the_United_States). It allows us to determine which region a given state belongs to (including Washington D.C.)

In [7]:
import pandas as pd

state_lst = [
    "Alabama", "Alaska", "Arizona", "Arkansas", "California",
    "Colorado", "Connecticut", "Delaware", "District of Columbia", "Florida",
    "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa",
    "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland",
    "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri",
    "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey",
    "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio",
    "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina",
    "South Dakota", "Tennessee", "Texas", "Utah", "Vermont",
    "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming"
]

region_lst = [
    "South", "West", "West", "South", "West",
    "West", "Northeast", "South", "South", "South",
    "South", "West", "West", "Midwest", "Midwest", "Midwest",
    "Midwest", "South", "South", "Northeast", "South",
    "Northeast", "Midwest", "Midwest", "South", "Midwest",
    "West", "Midwest", "West", "Northeast", "Northeast",
    "West", "Northeast", "South", "Midwest", "Midwest",
    "South", "West", "Northeast", "Northeast", "South",
    "Midwest", "South", "South", "West", "Northeast",
    "South", "West", "South", "Midwest", "West"
]

df_region = pd.DataFrame({"state": state_lst, "region":region_lst})

df_region.head()

        state region
0     Alabama  South
1      Alaska   West
2     Arizona   West
3    Arkansas  South
4  California   West

<font size = "4">

- Read in the file "president_county_candidate.csv" from the quiz_data folder, assigning it to a Pandas DataFrame.

- This dataset contains information about the total number of votes won by candidates during the 2020 U.S. presidential election on a county-by-county basis.

- Merge this DataFrame with `df_region` defined above. Perform the merge so that the columns are in the following order: "region", "state", "county", "candidate", "total_votes"

In [15]:
# your code here
pres = pd.read_csv("quiz_data/president_county_candidate.csv")

pres_merged = pd.merge(left = df_region[["region", "state"]], 
                       right = pres[["state", "county", "candidate", "total_votes"]], 
                       how = "left", 
                       on = "state")
pres_merged

      region    state           county     candidate  total_votes
0      South  Alabama  Cherokee County  Donald Trump        10583
1      South  Alabama  Cherokee County     Joe Biden         1624
2      South  Alabama  Cherokee County  Jo Jorgensen           82
3      South  Alabama  Cherokee County     Write-ins           12
4      South  Alabama   Chilton County  Donald Trump        16085
...      ...      ...              ...           ...          ...
32172   West  Wyoming    Weston County  Donald Trump         3107
32173   West  Wyoming    Weston County     Joe Biden          360
32174   West  Wyoming    Weston County  Jo Jorgensen           46
32175   West  Wyoming    Weston County  Brock Pierce           20
32176   West  Wyoming    Weston County     Write-ins            9

[32177 rows x 5 columns]

<font size = "4">

**Q4** Counting votes in a region

<font size = "3">

- For this question, use the merged DataFrame you created above.

- Use the `.query()` and `.sum()` methods to calculate how many total votes Gloria La Riva won in states belonging to the "West" region of the United States. Print this value (an integer) to the screen 

- Then try to compute the answer to the same question in a single line of code using "chaining".

In [27]:
# your code here

west = pres_merged.query("region == 'West' and candidate == 'Gloria La Riva'")
print(west["total_votes"].sum())

pres_merged.query("region == 'West' and candidate == 'Gloria La Riva'")["total_votes"].sum()

59690

np.int64(59690)

<font size = "4">


**Q5** Computing average votes for different regions

<font size = "3">

- For this question, continue to use the merged DataFrame you created in question 3.

- Use `.query` to extract the subset of the data corresponding to the candidate "Howie Hawkins".

- Use the `.groupby` method to calculate the average number of votes Howie Hawkins won in Midwest states, Northeast states, South states, and West states, respectively.

In [29]:
# your code here
hawkins = pres_merged.query("candidate == 'Howie Hawkins'")

hawkins_grouped = hawkins.groupby(by = "region")

hawkins_grouped["total_votes"].mean()

region
Midwest      156.970435
Northeast     61.351893
South        121.760198
West         507.346008
Name: total_votes, dtype: float64

<font size = "4">

**Q6** Recoding categorical variables

<font size = "3">

- Read in the familiar dataset `features.csv` from the quiz_data folder, assigning it to a DataFrame.

- Recode the "mpg" variable into a categorial variable with the values

    - "Low mileage" if $\textrm{mpg} \leq 20$
    - "Medium mileage" if $20 < \textrm{mpg} \leq 34$
    - "High mileage" if $34 < \textrm{mpg}$

- Do this in two different ways

    1. Using the `.apply` method.

    2. Using the function `pandas.cut`

In [ ]:
# your code here
cars = pd.read_csv("quiz_data/features.csv")

def check_mpg(mpg):
    if mpg <= 20:
        return "Low mileage"
    elif mpg <= 34:
        return "Medium mileage"
    elif mpg > 34:
        return "High mileage"
    else:
        return np.nan  ## ALWAYS be wary of NAs

cars["mileage"] = cars["mpg"].apply(check_mpg)

cars.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,vehicle id,mileage
0,18.0,8,307,130,3504,12.0,C-1689780,Low mileage
1,15.0,8,350,165,3693,11.5,B-1689791,Low mileage
2,18.0,8,318,150,3436,11.0,P-1689802,Low mileage
3,16.0,8,304,150,3433,12.0,A-1689813,Low mileage
4,17.0,8,302,140,3449,10.5,F-1689824,Low mileage

In [35]:
mpg_bins = [-np.inf, 20, 34, np.inf]
mpg_labels = ["Low mileage", "Medium mileage", "High mileage"]

cars["mymileage"] = pd.cut(cars["mpg"],
                           bins = mpg_bins,
                           right = True,
                           labels = mpg_labels)

cars.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,vehicle id,mileage,mymileage
0,18.0,8,307,130,3504,12.0,C-1689780,Low mileage,Low mileage
1,15.0,8,350,165,3693,11.5,B-1689791,Low mileage,Low mileage
2,18.0,8,318,150,3436,11.0,P-1689802,Low mileage,Low mileage
3,16.0,8,304,150,3433,12.0,A-1689813,Low mileage,Low mileage
4,17.0,8,302,140,3449,10.5,F-1689824,Low mileage,Low mileage